import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { useThisTemplateUrl } from "../template-repository.ts";
import { repoRoot, trackProjects } from "../tracks.ts";

const startMarker = "<!-- fieldwork:tracks:start -->";
const endMarker = "<!-- fieldwork:tracks:end -->";

/** A Track's own metadata, in tracks/<track>/track.json. */
interface TrackMetadata {
  title: string;
  summary: string;
  /** What a Learner installs before starting any of the Track's Projects. */
  prerequisites: string[];
  /** Starts the name of each of the Track's template repositories, e.g. "ts" (ADR-0003). */
  repositoryPrefix: string;
}

/** The fields of a Project's fieldwork.json that its listing shows. */
interface ProjectListing {
  name: string;
  summary: string;
  assumes: string[];
  concepts: string[];
  gitPractices: string[];
}

/**
 * Regenerates the Tracks and Projects listing in the monorepo README, between
 * its markers, from tracks/<track>/track.json and each Project's
 * fieldwork.json. With --check it only compares, returning 1 if the README has
 * drifted. Takes the monorepo directory, defaulting to this one.
 */
export async function readmeCommand(args: string[]): Promise<number> {
  const check = args.includes("--check");
  const positional = args.filter((arg) => arg !== "--check");
  if (positional.length > 1 || positional.some((arg) => arg.startsWith("--"))) {
    console.error("Usage: npm run fieldwork -- readme [--check] [<monorepo-dir>]");
    return 2;
  }
  const root = positional.length === 1 ? resolve(positional[0]!) : repoRoot;
  const readmePath = join(root, "README.md");

  const current = readFileSync(readmePath, "utf8");
  const start = current.indexOf(startMarker);
  const end = current.indexOf(endMarker);
  if (start === -1 || end < start) {
    throw new Error(`${readmePath} needs a line ${startMarker} followed later by a line ${endMarker}, to mark where the listings go.`);
  }
  const updated = current.slice(0, start + startMarker.length) + "\n" + listings(root) + current.slice(end);

  if (check) {
    if (updated === current) {
      console.log("README.md matches the Track and Project metadata.");
      return 0;
    }
    console.log("README.md has drifted from the Track and Project metadata. Run `npm run fieldwork -- readme` and commit the result.");
    return 1;
  }
  writeFileSync(readmePath, updated);
  console.log(updated === current ? "README.md is already up to date." : "Updated README.md.");
  return 0;
}

function listings(root: string): string {
  const tracksDir = join(root, "tracks");
  const sections = readdirSync(tracksDir)
    .filter((track) => existsSync(join(tracksDir, track, "track.json")))
    .sort()
    .map((track) => trackSection(root, join(tracksDir, track)));
  return [
    "<!-- Generated by `npm run fieldwork -- readme` from tracks/*/track.json and each Project's fieldwork.json. Edit those, not this section. -->",
    ...sections,
  ].join("\n\n") + "\n";
}

function trackSection(root: string, trackDir: string): string {
  const track = readTrack(root, join(trackDir, "track.json"));
  const projects = trackProjects(trackDir).map((dir) => readProject(root, join(dir, "fieldwork.json")));

  return [
    `## ${track.title}`,
    track.summary,
    `Before you start, install:\n\n${bullets(track.prerequisites)}`,
    ...(projects.length === 0 ? ["No Projects yet."] : projects.map((project) => projectSection(track, project))),
  ].join("\n\n");
}

function projectSection(track: TrackMetadata, { name, summary, assumes, concepts, gitPractices }: ProjectListing): string {
  return [
    `### ${name}`,
    summary,
    `**Assumes you know:**\n\n${bullets(assumes)}`,
    `**Language concepts:**\n\n${bullets(concepts)}`,
    `**Git practices:**\n\n${bullets(gitPractices)}`,
    `[Use this template](${useThisTemplateUrl(track.repositoryPrefix, name)}) to create your own repository for this Project, then follow its README.`,
  ].join("\n\n");
}

function bullets(items: string[]): string {
  return items.map((item) => `- ${item}`).join("\n");
}

function readTrack(root: string, path: string): TrackMetadata {
  const json = readJson(path);
  const where = relative(root, path);
  return {
    title: requireString(json, "title", where),
    summary: requireString(json, "summary", where),
    prerequisites: requireStrings(json, "prerequisites", where),
    repositoryPrefix: requireString(json, "repositoryPrefix", where),
  };
}

function readProject(root: string, path: string): ProjectListing {
  const json = readJson(path);
  const where = relative(root, path);
  return {
    name: requireString(json, "name", where),
    summary: requireString(json, "summary", where),
    assumes: requireStrings(json, "assumes", where),
    concepts: requireStrings(json, "concepts", where),
    gitPractices: requireStrings(json, "gitPractices", where),
  };
}

function readJson(path: string): Record<string, unknown> {
  return JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
}

function requireString(json: Record<string, unknown>, field: string, where: string): string {
  const value = json[field];
  if (typeof value !== "string" || value.trim() === "") throw new Error(`${where} needs "${field}": a non-empty string.`);
  return value;
}

function requireStrings(json: Record<string, unknown>, field: string, where: string): string[] {
  const value = json[field];
  if (!Array.isArray(value) || value.length === 0 || value.some((item) => typeof item !== "string" || item.trim() === "")) {
    throw new Error(`${where} needs "${field}": a non-empty list of strings.`);
  }
  return value as string[];
}
